// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/binanceexchange_user/v1/binanceexchange_user.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SetUserRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SetUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SetUserRequestMultiError,
// or nil if none found.
func (m *SetUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSendBody()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SetUserRequestValidationError{
					field:  "SendBody",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SetUserRequestValidationError{
					field:  "SendBody",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSendBody()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SetUserRequestValidationError{
				field:  "SendBody",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SetUserRequestMultiError(errors)
	}

	return nil
}

// SetUserRequestMultiError is an error wrapping multiple validation errors
// returned by SetUserRequest.ValidateAll() if the designated constraints
// aren't met.
type SetUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetUserRequestMultiError) AllErrors() []error { return m }

// SetUserRequestValidationError is the validation error returned by
// SetUserRequest.Validate if the designated constraints aren't met.
type SetUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetUserRequestValidationError) ErrorName() string { return "SetUserRequestValidationError" }

// Error satisfies the builtin error interface
func (e SetUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetUserRequestValidationError{}

// Validate checks the field values on SetUserReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SetUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetUserReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SetUserReplyMultiError, or
// nil if none found.
func (m *SetUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SetUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SetUserReplyMultiError(errors)
	}

	return nil
}

// SetUserReplyMultiError is an error wrapping multiple validation errors
// returned by SetUserReply.ValidateAll() if the designated constraints aren't met.
type SetUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetUserReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetUserReplyMultiError) AllErrors() []error { return m }

// SetUserReplyValidationError is the validation error returned by
// SetUserReply.Validate if the designated constraints aren't met.
type SetUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetUserReplyValidationError) ErrorName() string { return "SetUserReplyValidationError" }

// Error satisfies the builtin error interface
func (e SetUserReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetUserReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetUserReplyValidationError{}

// Validate checks the field values on SetUserRequest_SendBody with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetUserRequest_SendBody) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetUserRequest_SendBody with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetUserRequest_SendBodyMultiError, or nil if none found.
func (m *SetUserRequest_SendBody) ValidateAll() error {
	return m.validate(true)
}

func (m *SetUserRequest_SendBody) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	// no validation rules for Apikey

	// no validation rules for Apisecret

	if len(errors) > 0 {
		return SetUserRequest_SendBodyMultiError(errors)
	}

	return nil
}

// SetUserRequest_SendBodyMultiError is an error wrapping multiple validation
// errors returned by SetUserRequest_SendBody.ValidateAll() if the designated
// constraints aren't met.
type SetUserRequest_SendBodyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetUserRequest_SendBodyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetUserRequest_SendBodyMultiError) AllErrors() []error { return m }

// SetUserRequest_SendBodyValidationError is the validation error returned by
// SetUserRequest_SendBody.Validate if the designated constraints aren't met.
type SetUserRequest_SendBodyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetUserRequest_SendBodyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetUserRequest_SendBodyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetUserRequest_SendBodyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetUserRequest_SendBodyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetUserRequest_SendBodyValidationError) ErrorName() string {
	return "SetUserRequest_SendBodyValidationError"
}

// Error satisfies the builtin error interface
func (e SetUserRequest_SendBodyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetUserRequest_SendBody.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetUserRequest_SendBodyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetUserRequest_SendBodyValidationError{}
